music/urls.py
from django.conf.urls import url

from music import views
app_name= 'music'  # required for namespace
urlpatterns= [
    #/music/
    url(r'^$', views.index, name='index'),

    #/music/register
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /music/71/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    #/music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    #/music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$',views.AlbumUpdate.as_view(), name='album-update'),

    #/music/album/2/delete/
    url(r'album/(?P<pk>[0-9]+)/delete/$',views.AlbumDelete.as_view(), name='album-delete'),

    #/music/login/
    url(r'^login/$',views.LoginView.as_view(), name='login'),

    #/music/logout/
    url(r'^logout/$',views.logout_user,name='logout'),

    #/music/songs/all/
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),

    #/music/71/add/
    url(r'^(?P<pk>[0-9]+)/add/$', views.SongCreate.as_view(), name='song-add'),

    #/music/song/22/favorite    or     #/music/song/22/favourite
    url(r'^song/(?P<pk>[0-9]+)/favorite/$', views.favorite_song, name='fav_song'),
    url(r'^song/(?P<pk>[0-9]+)/favourite/$', views.favorite_song, name='fav_song'),

    
]

myfirst/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/',include('music.urls'))
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import Permission, User
from django.db import models

from django.urls import reverse


# Create your models here.
class Album(models.Model):
    user= models.ForeignKey(User, default=1,on_delete=models.DO_NOTHING)
    artist= models.CharField(max_length=100)
    album_title= models.CharField(max_length=200)
    genre= models.CharField(max_length=50)
    album_logo= models.FileField()
    album_favorite= models.BooleanField(default=False)


    def get_absolute_url(self):
        return reverse('music:detail',kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title+' by '+ self.artist

class Song(models.Model):
    album= models.ForeignKey('Album', on_delete=models.CASCADE)
    song_title= models.CharField(max_length=200)
    audio_file= models.FileField(default='')
    is_favorite= models.BooleanField(default=False)
    def __str__(self):
        return self.song_title

    def get_absolute_url(self):
        alb= self.album
        return reverse('music:detail',kwargs={'pk':alb.pk})

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password= forms.CharField(widget= forms.PasswordInput)
    class Meta:
        model= User
        fields= ['username','email','password']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Album, Song
from django.urls import reverse_lazy

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from .forms import UserForm
from django.http import JsonResponse
from django.db.models import Q


def index(request):
        if not request.user.is_authenticated:
            return render(request, 'music/login_form.html')
        else:
            albums= Album.objects.filter(user=request.user)
            num= Album.objects.filter(user=request.user).count()
            req= request.GET.get("q")
            if req:
                songs=Song.objects.filter(album=albums)
                albums= albums.filter(
                    Q(album_title__icontains=req) |
                    Q(artist__icontains=req)
                ).distinct()
                songs=songs.filter(
                    Q(song_title__icontains=req)
                ).distinct()
                context={
                'object_list': albums,
                'num': num,
                'songs': songs
                }
            else :
                context={
                'object_list': albums,
                'num': num
                }
            return render(request, 'music/index.html', context) #we are using onject_list here coz for learning classbasedgen views we did the rest accordingly



class DetailView(LoginRequiredMixin, generic.DetailView):
    login_url= 'music:login'
    redirect_field_name= 'go_to'
    model= Album
    template_name= 'music/detail.html'

    def get_context_data(self, *args, **kwargs):
        temp_album= Album.objects.get(pk=self.kwargs['pk'])
        kwargs['song_list']= Song.objects.filter(album= temp_album)
        #kwargs['song_list']= Album.objects.select_related().filter(pk= self.kwargs['pk'])
        return super(DetailView, self).get_context_data(*args, **kwargs)




class SongCreate(LoginRequiredMixin, CreateView):

    login_url='music:login'
    redirect_field_name='go_to'
    model=Song
    fields=['song_title','audio_file']

    def get_context_data(self, *args, **kwargs):
        kwargs['album']= Album.objects.get(pk= self.kwargs['pk'])
        return super(SongCreate, self).get_context_data(*args, **kwargs)


    def form_valid(self, form):
        temp= form.save(commit=False)
        temp.album= Album.objects.get(pk= self.kwargs['pk'])
        temp.save()
        return super(SongCreate, self).form_valid(form)



class AlbumCreate(LoginRequiredMixin, CreateView):
    login_url= 'music:login'
    redirect_field_name='go_to'
    model=Album
    fields=['artist','album_title','genre','album_logo']

    def form_valid(self, form):
        temp= form.save(commit=False)
        temp.user= self.request.user
        temp.save()
        return super(AlbumCreate, self).form_valid(form)






class AlbumUpdate(LoginRequiredMixin, UpdateView):
    login_url= 'music:login'
    redirect_field_name='go_to'
    model=Album
    fields=['artist','album_title','genre','album_logo']

    def form_valid(self, form):
        temp=form.save(commit=False)
        temp.user= self.request.user
        temp.save()
        return super(AlbumUpdate, self).form_valid(form)


class AlbumDelete(LoginRequiredMixin, DeleteView):
    login_url= 'music:login'
    redirect_field_name= 'go_to'
    model=Album
    #success_url= reverse_lazy('music:index')
    def get_success_url(self):
        return reverse_lazy('music:index')

class UserFormView(View):
    form_class= UserForm
    template_name= 'music/registration_form.html'

    def get(self, request): #display blank form for registration
        form= self.form_class(None)
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form= self.form_class(request.POST)

        if form.is_valid():
            user= form.save(commit=False)

            username= form.cleaned_data['username']
            password= form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #returns user obj if login creds are correct
            user= authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form':form})


class LoginView(View):

    def get(self, request): #display blank form for logging in
        return render(request,'music/login_form.html')

    def post(self, request):

        username= request.POST.get('username')
        password= request.POST.get('password')

        #returns user obj if login creds are correct
        user= authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/music/')
        else:
            return render(request, 'music/login_form.html', {'error_message':'Not a valid username and pwd. Try Again or make sure that you are a registered user'}) 
        return render(request, 'music/login_form.html')


def logout_user(request):

    if not request.user.is_authenticated:
        return redirect('/music/login/')
    else :
        logout(request)
        return redirect('/music/login/')

def songs(request, filter_by):
    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        try:
            song_ids = []
            for album in Album.objects.filter(user=request.user):
                for song in album.song_set.all():
                    song_ids.append(song.pk)
            users_songs = Song.objects.filter(pk__in=song_ids)
            if filter_by == 'favorites':
                users_songs = users_songs.filter(is_favorite=True)
        except Album.DoesNotExist:
            users_songs = []
        return render(request, 'music/music_home.html', {
            'song_list': users_songs,
            'filter_by': filter_by,
})

def favorite_song(request,pk):

    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        song= Song.objects.get(pk=pk)
        idee= song.album.pk
        if song.is_favorite:
            song.is_favorite= False
        else:
            song.is_favorite= True
        song.save()
        return redirect('music:songs','favorites')

music/templates/music/album_confirm_delete.html
{% extends 'music/base.html' %}
{% block title %}Playspa{% endblock %}
{% block body %}
  <form method="post" id="confirm">
    {% csrf_token %}
    <div style="background-color:white;margin:50px 600px 0px 200px;padding: 10px 0px 20px 120px">
      <label align="center" style="font-size:20px">are you sure you want to delete the album</label></br>
      <a href="{% url 'music:index' %}" >
        <button type="button" value="No, go back" class="btn btn-warning">No, go back</button>
      </a> &nbsp &nbsp
      <button type="submit" value="confirm" class="btn btn-success">Confirm</button>
    </div>
  </form>
  <script>

  </script>
{% endblock %}

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add new Album{% endblock %}

{% block body %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12 col-md-7">
        <div class ="panel panel-default">
          <div class="panel-body">
            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% include 'music/form-template.html' %}
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-success">
                    Submit
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

music/templates/music/album_thumbnail.html
{% extends 'music/base.html'  %}
{% load staticfiles %}

{% block body %}

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-4 col-md-3">
        <div class="panel panel-default">
          <div class="panel-body">
            <a href="{% url 'music:detail' album.id %}">
              {% if album.album_logo %}
                <img src="{{ album.album_logo.url }}" class="img-responsive">
              {% else %}
                <h3>No image to display</h3>
              {% endif %}
            </a>
            <h2> <b>{{ album.album_title }} </b></h2>
            <h2> <small>{{ album.genre }}</small></h2>
            <h2> {{ album.artist }} </h2>
          </div>
        </div>
      </div>

      {% block right_to_thumbnail %}{% endblock %}
    </div>
  </div>

{% endblock %}

music/templates/music/base.html
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <!-- load the path to your static files -->
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style_base.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
    {% block heads %}{% endblock %}
  </head>


  <body>

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'music:index' %}" > Playspa </a>
        </div>


        <div class="collapse navbar-collapse" id="topNavBar">

          <ul class="nav navbar-nav">
            <li class="active">
              <a href="{% url 'music:index' %}">
                <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                Album
              </a>
            </li>

            <li class="">
              <a href="{% url 'music:songs' 'all' %}">
                <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                Music
              </a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="{% url 'music:album-add' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                Add Album
              </a>
            </li>
            <li class="">
              <a href="{% url 'music:logout' %}">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                Logout
              </a>
            </li>
          </ul>
          <form class="navbar-form navbar-right" role="search" method="get" action="">
            <div class="form-group">
              <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
              <button type="submit" class="btn btn-default" style="padding-top: 8px;padding-bottom: 8px;">
                <span class="glyphicon glyphicon-search"></span>
              </button>
            </div>
          </form>



        </div>

      </div>
    </nav>

    {% block body %}
    {% endblock %}

  </body>
</html>

music/templates/music/base_new.html
<!DOCTYPE html>
<html>


  <head>

    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style_base.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

  </head>



  <body>

      <nav class="navbar navbar-inverse">
        <div class="container-fluid">


          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Playspa</a>
          </div>

          <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav navbar-right">
              <li class="{% block templ_login %}{% endblock %}"><a href="{% url 'music:login' %}">Log In</a></li>
              <li class="{% block templ_register %}{% endblock %}"><a href="{% url 'music:register' %}">Register</a></li>
            </ul>
          </div>
        </div>
      </nav>
      {% block body %}
      {% endblock %}
  </body>

</html>

music/templates/music/detail.html
{% extends 'music/album_thumbnail.html' %}
{% block title %}Details{% endblock %}
{% load staticfiles %}

{% block right_to_thumbnail %}
  <div class="col-sm-8 col-md-9">

    <ul class="nav nav-pills" >
      <li role="presentation" class="active">
        <a href="{% url 'music:detail' album.id %}">This Album</a>
      </li>
      <li role="presentation">
        <a href="{% url 'music:song-add' album.id %}">Add a Song</a>
      </li>
    </ul>

    <div class="panel panel-default">
      <div class="panel-body">
        <table class="table">
          <thead>
            <th>song</th>
            <th>song file</th>
            <th>favorite</th>
            <th>actions</th>
          </thead>
              
          <tbody>
            {% for song in song_list %}
              <tr>  
                <td> {{ song.song_title }}</td>
                <td>
                  <a target="_blank" href="{{ song.audio_file.url }}">
                    <button type="button" class="btn btn-success btn-xs">
                      <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                    </button>
                  </a>
                </td>
                <td>
                  <a href="{% url 'music:fav_song' song.id %}" class="btn-favorite">
                    <span class="glyphicon glyphicon-star {% if song.is_active %} active {% endif %}"></span>
                  </a>
                </td>
                <td>
                  <a href="#">
                    <button type="button" class="btn btn-danger btn-xs">
                      <span class="glyphicon glyphicon-trash"></span>&nbsp; Remove
                    </button>
                  </a>
                </td>

              </tr>
            {% endfor %}       
          </tbody>

        </table>
      </div>
    </div>
  </div>
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2-col-sm-10">
      <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2">
      {{field.label_tag}}
    </label>
      <div class="col-sm-10">{{ field }}</div>
  </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% load staticfiles %}

{% block title %}Playspa{% endblock %}

{% block heads %}
  <link rel="stylesheet" type="text/css" href="{% static 'music/style_ind.css' %}" />
{% endblock %}

{% block body %}

  <div class="parentmost-container">

    <div class="heading-container">
      <h2 style="color:white"> {{ user.username }}'s Albums </h2>
    </div>
    <h5 style="margin-top:25px"> {{ user.username }} has {{ num }} albums </h5>


    <div class="playground container-fluid rounded" >
      <div class="row">

        {% if object_list %}
          {% for album in object_list %}  <!-- we use object_list here without actual requirement-->

            <div class="col-sm-4 col-md-3 col-lg-3 each-album" style="background-color:#515356; border-radius:10px">

              <div class="image-container" style="margin-top:40px;">
                <a href="{% url 'music:detail' album.id %}">
                  <img src="{{ album.album_logo.url }}" class="img-responsive img-thumbnail"/>
                </a>
              </div>

              <div class="caption">

                <h3 style="color:white;"> {{ album.album_title }} </h3>
                <h4 style="color:white;"> {{ album.artist}} </h4>

                <a href="{% url 'music:detail' album.id %}" role="button" class="btn btn-primary btn-md">view</a>
                <script>
                  function delConfirm(){
                    if(confirm("Are you sure you want to delete this album"))
                    {  return true;}
                    return false;
                  }
                </script>
                <form action="{% url 'music:album-delete' album.id %}">
                  {% csrf_token %}
                  <button type="button" onclick="return delConfirm()">
                    <span class="glyphicon glyphicon-trash" style="color:red;"></span>
                  </button>
                </form>

              </div>

            </div>
            {% cycle '' '' '' '<div class="clearfix visible-lg"></div>' %}
          {% endfor %}
        {% endif %}

      </div>
    </div>
  </div>
  {% if songs %}  
    <div class="container-fluid song-container" style="margin-top: 50px;">
      <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-body">
              <table class="table">
                <thead>
                  <tr>
                    <th>Song</th>
                    <th>Audio file</th>
                    <th>Album</th>
                    <th>Artist</th>
                  </tr>
                </thead>
                <tbody>
                  {% for song in songs %}
                    <tr>
                      <td>
                        {{ song.song_title }}
                      </td>
                      <td>
                        <a target="_blank" href="{{ song.audio_file.url }}">
                          <button type="button" class="btn btn-success btn-xs">
                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                          </button>
                        </a>
                      </td>
                      <td>
                        <a href="{% url 'music:detail' song.album.pk %}">
                            {{ song.album.album_title }}
                        </a>
                      </td>
                      <td>{{ song.album.artist }}</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
  <!--
    <form id="form_uord" method="post" >
      <ol>
        {% for album in object_list %} <!-- object_list is the default
          where the data returned by the view is stored in the html script -->
      <!--
        <li>
          <a href="{% url 'music:detail' album.id %}">{{ album.album_title}}</a>
          &nbsp &nbsp &nbsp &nbsp
          <a href="{% url 'music:album-update' album.id %}" >
            <button id="update_button" type="button" value="update" class="btn btn-primary"> update</button>
          </a>
          &nbsp &nbsp
          <a href="{% url 'music:album-delete' album.id %}" >
            <button id="delete_button" type="button" value="delete" class="btn btn-danger" > delete </button>
          </a>
          </br></br>
        </li>
        {% endfor %}
      </ol>
    </form>

    <script>

      function upd(url_upd)
      {
        var f= document.getElementById("form_uord");
        f.action=url_upd;
        var but=document.getElementById("update_button");
        but.type="submit";
        document.getElementById("form_uord").submit();
      }
      function del(url_del)
      {
        var f= document.getElementById("form_uord");
        f.action=url_del;
        var but=document.getElementById("delete_button");
        but.type="submit";
        document.getElementById("form_uord").submit();
      }
    </script>
  -->
{% endblock %}

music/templates/music/login_form.html
{% extends 'music/base_new.html' %}
{% block title %}Log In{% endblock %}
{% block templ_login %}active{% endblock %}
{% block body %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <div class="panel panel-default">
          <div class="panel-body">

            <h3> Log In </h3>
            {% if error_message %}
              <p style="color:red;"><strong>{{ error_message }}</strong></p>
            {% endif %}
            <form class="" method="post" role="form" action="{% url 'music:login' %}" enctype="multipart/form-data">
              {% csrf_token %}

              <div class="form-group">
                <label class="control-label col-sm-2" for="id_username">
                  Username:
                </label>
                <div class="col-sm-10">
                  <input id="id_username" maxlength="30" name="username" type="text">
                </div>
              </div>

              <div class="form-group">
                <label class="control-label col-sm-2" for="id_password">
                  Password:
                </label>
                <div class="col-sm-10">
                  <input id="id_password" maxlength="30" name="password" type="password">
                </div>
              </div>

              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-success">Submit</button>
                </div>
              </div>
            </form>
          </div>
          <div class="panel-footer">
            Don't have an account? <a href="{% url 'music:register' %}">Click here</a> to register.
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

music/templates/music/music_home.html
{% extends 'music/base.html' %}
{% block title %}All Songs{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}>
                  <a href="{% url 'music:songs' 'all' %}">View All</a>
                </li>
                <li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}>
                  <a href="{% url 'music:songs' 'favorites' %}">Favorites</a>
                </li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Album</th>
                                <th>Favorite</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in song_list %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>{{ song.album.artist }}</td>
                                    <td>
                                        <a target="_blank" href="{{ song.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:detail' song.album.id %}">
                                            <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:fav_song' song.id %}" class="btn-favorite">
                                          <span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base_new.html' %}
{% block title %}Registration{% endblock %}
{% block templ_register %}active{% endblock %}
{% block body %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <div class ="panel panel-default">
          <div class="panel-body">
            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% include 'music/form-template.html' %}
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-success">
                    Submit
                  </button>
                </div>
              </div>
            </form>
          </div>
          <div class="panel-footer">
            Already have an account? Click <a href="{% url 'music:login' %}">here</a> to login.
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

music/templates/music/song_form.html
{% extends 'music/album_thumbnail.html' %}
{% block title %}Add a Song{% endblock %}
{% load staticfiles %}

{% block right_to_thumbnail %}

  <div class="col-sm-8 col-md-9">

    <ul class="nav nav-pills" >
      <li role="presentation" >
        <a href="{% url 'music:detail' album.id %}">This Album</a>
      </li>
      <li role="presentation" class="active">
        <a href="#">Add a Song</a>
      </li>
    </ul>

    <div class="panel panel-default">
      <div class="panel-body">
        <h3> Add a new Song here</h3>
        {% if error_messege %}
          <p><strong>{{ error_message }}</strong></p>
        {% endif %}

        <form class="form-horizontal" role="form" method="post" action="" enctype="multipart/form-data">
          {% csrf_token %}
          <input type="hidden" name="album" value="{{ album }}">
          {% include 'music/form-template.html' %}
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-success">Submit</button>
            </div>
          </div>

        </form>
      </div>
    </div>


  </div>
{% endblock %}